Repository k2-fsa/icefall, pull requests merged in 2022-07, with the labels that each got.

#464 Add multi_quantization to requirements.txt
  .github/scripts/run-aishell-pruned-transducer-stateless3-2022-06-20.sh
  .github/scripts/run-librispeech-pruned-transducer-stateless5-2022-05-13.sh
  requirements-ci.txt
  requirements.txt
Labels: ready, run-decode

#467 Rand combine update result
  egs/librispeech/ASR/RESULTS.md
  egs/librispeech/ASR/pruned_transducer_stateless5/conformer.py
Labels: ready

#465 [Ready] [Recipes] add aishell2
  egs/aishell2/ASR/README.md
  egs/aishell2/ASR/RESULTS.md
  egs/aishell2/ASR/local/__init__.py
  egs/aishell2/ASR/local/compute_fbank_aishell2.py
  egs/aishell2/ASR/local/compute_fbank_musan.py
  egs/aishell2/ASR/local/display_manifest_statistics.py
  egs/aishell2/ASR/local/prepare_char.py
  egs/aishell2/ASR/local/prepare_lang.py
  egs/aishell2/ASR/local/prepare_words.py
  egs/aishell2/ASR/local/text2segments.py
  egs/aishell2/ASR/local/text2token.py
  egs/aishell2/ASR/prepare.sh
  egs/aishell2/ASR/pruned_transducer_stateless5/__init__.py
  egs/aishell2/ASR/pruned_transducer_stateless5/asr_datamodule.py
  egs/aishell2/ASR/pruned_transducer_stateless5/beam_search.py
  egs/aishell2/ASR/pruned_transducer_stateless5/conformer.py
  egs/aishell2/ASR/pruned_transducer_stateless5/decode.py
  egs/aishell2/ASR/pruned_transducer_stateless5/decoder.py
  egs/aishell2/ASR/pruned_transducer_stateless5/encoder_interface.py
  egs/aishell2/ASR/pruned_transducer_stateless5/export.py
  egs/aishell2/ASR/pruned_transducer_stateless5/joiner.py
  egs/aishell2/ASR/pruned_transducer_stateless5/model.py
  egs/aishell2/ASR/pruned_transducer_stateless5/optim.py
  egs/aishell2/ASR/pruned_transducer_stateless5/pretrained.py
  egs/aishell2/ASR/pruned_transducer_stateless5/scaling.py
  egs/aishell2/ASR/pruned_transducer_stateless5/train.py
  egs/aishell2/ASR/shared
  egs/wenetspeech/ASR/local/prepare_words.py
Labels: ready

#481 Add compile_lg.py for aishell2 recipe
  egs/aishell2/ASR/local/compile_lg.py
Labels: ready

#475 Add RNN-LM rescoring in fast beam search
  egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py
  egs/librispeech/ASR/pruned_transducer_stateless3/decode.py
  icefall/decode.py
Labels: ready, run-decode

#483 Fix diagnostic
  icefall/diagnostics.py
Labels: ready

#484 Update conformer.py for aishell4
  egs/aishell4/ASR/pruned_transducer_stateless5/conformer.py
  egs/aishell4/ASR/pruned_transducer_stateless5/decode.py
  egs/aishell4/ASR/pruned_transducer_stateless5/export.py
Labels: ready

#492 Update doc to add a link to Nadira Povey's YouTube channel.
  .github/workflows/build-doc.yml
  README.md
  docs/requirements.txt
  docs/source/conf.py
  docs/source/huggingface/index.rst
  docs/source/huggingface/pic/hugging-face-sherpa-2.png
  docs/source/huggingface/pic/hugging-face-sherpa-3.png
  docs/source/huggingface/pic/hugging-face-sherpa.png
  docs/source/huggingface/pretrained-models.rst
  docs/source/huggingface/spaces.rst
  docs/source/index.rst
  docs/source/installation/index.rst
  docs/source/recipes/librispeech/conformer_ctc.rst
  docs/source/recipes/librispeech/tdnn_lstm_ctc.rst
Labels: doc

#485 Add stats about duration and padding proportion
  egs/librispeech/ASR/conv_emformer_transducer_stateless/train.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless2/train.py
  egs/librispeech/ASR/pruned_stateless_emformer_rnnt2/train.py
  egs/librispeech/ASR/pruned_transducer_stateless/train.py
  egs/librispeech/ASR/pruned_transducer_stateless2/train.py
  egs/librispeech/ASR/pruned_transducer_stateless3/train.py
  egs/librispeech/ASR/pruned_transducer_stateless4/train.py
  egs/librispeech/ASR/pruned_transducer_stateless5/train.py
  egs/librispeech/ASR/pruned_transducer_stateless6/train.py
  icefall/utils.py
Labels: ready

#489 Add modified_beam_search for streaming decode
  .github/scripts/run-librispeech-streaming-pruned-transducer-stateless2-2022-06-26.sh
  egs/librispeech/ASR/pruned_transducer_stateless/beam_search.py
  egs/librispeech/ASR/pruned_transducer_stateless/decode_stream.py
  egs/librispeech/ASR/pruned_transducer_stateless/streaming_beam_search.py
  egs/librispeech/ASR/pruned_transducer_stateless/streaming_decode.py
  egs/librispeech/ASR/pruned_transducer_stateless2/streaming_beam_search.py
  egs/librispeech/ASR/pruned_transducer_stateless2/streaming_decode.py
  egs/librispeech/ASR/pruned_transducer_stateless3/streaming_beam_search.py
  egs/librispeech/ASR/pruned_transducer_stateless3/streaming_decode.py
  egs/librispeech/ASR/pruned_transducer_stateless4/streaming_beam_search.py
  egs/librispeech/ASR/pruned_transducer_stateless4/streaming_decode.py
Labels: run-decode

#494 Fix using G before assignment in pruned_transducer_stateless/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless3/decode.py
Labels: run-decode

#506 A correction of directory name for prepare.sh
  egs/wenetspeech/ASR/prepare.sh
Labels: ready

#482 Add other decoding methods (nbest, nbest oracle, nbest LG) for wenetspeech pruned rnnt2
  README.md
  egs/wenetspeech/ASR/RESULTS.md
  egs/wenetspeech/ASR/local/compile_lg.py
  egs/wenetspeech/ASR/prepare.sh
  egs/wenetspeech/ASR/pruned_transducer_stateless2/decode.py
Labels: ready

#454 Support dynamic chunk streaming training in pruned_transcuder_stateless5
  egs/librispeech/ASR/RESULTS.md
  egs/librispeech/ASR/pruned_transducer_stateless5/conformer.py
  egs/librispeech/ASR/pruned_transducer_stateless5/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless5/decode_stream.py
  egs/librispeech/ASR/pruned_transducer_stateless5/export.py
  egs/librispeech/ASR/pruned_transducer_stateless5/streaming_beam_search.py
  egs/librispeech/ASR/pruned_transducer_stateless5/streaming_decode.py
  egs/librispeech/ASR/pruned_transducer_stateless5/train.py
Labels: ready
