Repository k2-fsa/icefall, pull requests merged in 2022-11, with the labels that each got.

#598 Get timestamps during decoding
  egs/librispeech/ASR/add_alignments.sh
  egs/librispeech/ASR/local/add_alignment_librispeech.py
  egs/librispeech/ASR/lstm_transducer_stateless3/decode.py
  egs/librispeech/ASR/lstm_transducer_stateless3/train.py
  egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py
  egs/librispeech/ASR/pruned_transducer_stateless4/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless4/train.py
  icefall/utils.py
Labels: ready

#622 Add fast_beam_search_LG
  .github/scripts/run-librispeech-pruned-transducer-stateless2-2022-04-29.sh
  .github/scripts/run-librispeech-pruned-transducer-stateless3-2022-04-29.sh
  egs/librispeech/ASR/pruned_transducer_stateless/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py
  egs/librispeech/ASR/pruned_transducer_stateless2/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless3/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless4/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless5/decode.py
  icefall/utils.py
Labels: run-decode

#654 Apply delay penalty on transducer
  .github/workflows/test.yml
  egs/librispeech/ASR/lstm_transducer_stateless/model.py
  egs/librispeech/ASR/lstm_transducer_stateless/train.py
  egs/librispeech/ASR/lstm_transducer_stateless2/model.py
  egs/librispeech/ASR/lstm_transducer_stateless2/train.py
  egs/librispeech/ASR/lstm_transducer_stateless3/train.py
  egs/librispeech/ASR/pruned_transducer_stateless/test_model.py
  egs/librispeech/ASR/pruned_transducer_stateless2/model.py
  egs/librispeech/ASR/pruned_transducer_stateless2/train.py
  egs/librispeech/ASR/pruned_transducer_stateless3/model.py
  egs/librispeech/ASR/pruned_transducer_stateless3/train.py
  egs/librispeech/ASR/pruned_transducer_stateless4/train.py
  egs/librispeech/ASR/pruned_transducer_stateless5/train.py
Labels: ready

#660 Refactor getting timestamps in fsa-based decoding
  egs/librispeech/ASR/lstm_transducer_stateless3/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py
  egs/librispeech/ASR/pruned_transducer_stateless4/decode.py
  icefall/utils.py
Labels: ready

#676 Fix shallow fusion and add CI tests for it
  .github/scripts/run-librispeech-lstm-transducer-stateless2-2022-09-03.yml
  .github/workflows/run-librispeech-lstm-transducer-stateless2-2022-09-03.yml
  egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py
  egs/librispeech/ASR/pruned_transducer_stateless2/decoder.py
Labels: shallow-fusion

#698 [recipe] AMI Zipformer transducer
  egs/ami/ASR/README.md
  egs/ami/ASR/RESULTS.md
  egs/ami/ASR/local/__init__.py
  egs/ami/ASR/local/compute_fbank_ami.py
  egs/ami/ASR/local/compute_fbank_musan.py
  egs/ami/ASR/local/prepare_ami_enhanced.py
  egs/ami/ASR/local/prepare_ami_gss.sh
  egs/ami/ASR/local/prepare_lang_bpe.py
  egs/ami/ASR/local/train_bpe_model.py
  egs/ami/ASR/prepare.sh
  egs/ami/ASR/pruned_transducer_stateless7/__init__.py
  egs/ami/ASR/pruned_transducer_stateless7/asr_datamodule.py
  egs/ami/ASR/pruned_transducer_stateless7/beam_search.py
  egs/ami/ASR/pruned_transducer_stateless7/decode.py
  egs/ami/ASR/pruned_transducer_stateless7/decoder.py
  egs/ami/ASR/pruned_transducer_stateless7/encoder_interface.py
  egs/ami/ASR/pruned_transducer_stateless7/export.py
  egs/ami/ASR/pruned_transducer_stateless7/joiner.py
  egs/ami/ASR/pruned_transducer_stateless7/model.py
  egs/ami/ASR/pruned_transducer_stateless7/optim.py
  egs/ami/ASR/pruned_transducer_stateless7/scaling.py
  egs/ami/ASR/pruned_transducer_stateless7/scaling_converter.py
  egs/ami/ASR/pruned_transducer_stateless7/train.py
  egs/ami/ASR/pruned_transducer_stateless7/zipformer.py
  egs/ami/ASR/shared
Labels: ready

#669 Apply delay penalty on k2 ctc loss
  .flake8
  .github/scripts/run-librispeech-conformer-ctc3-2022-11-28.sh
  .github/workflows/run-librispeech-conformer-ctc3-2022-11-28.yml
  egs/librispeech/ASR/RESULTS.md
  egs/librispeech/ASR/conformer_ctc3/__init__.py
  egs/librispeech/ASR/conformer_ctc3/asr_datamodule.py
  egs/librispeech/ASR/conformer_ctc3/conformer.py
  egs/librispeech/ASR/conformer_ctc3/decode.py
  egs/librispeech/ASR/conformer_ctc3/encoder_interface.py
  egs/librispeech/ASR/conformer_ctc3/export.py
  egs/librispeech/ASR/conformer_ctc3/jit_pretrained.py
  egs/librispeech/ASR/conformer_ctc3/lstmp.py
  egs/librispeech/ASR/conformer_ctc3/model.py
  egs/librispeech/ASR/conformer_ctc3/optim.py
  egs/librispeech/ASR/conformer_ctc3/pretrained.py
  egs/librispeech/ASR/conformer_ctc3/scaling.py
  egs/librispeech/ASR/conformer_ctc3/scaling_converter.py
  egs/librispeech/ASR/conformer_ctc3/test_model.py
  egs/librispeech/ASR/conformer_ctc3/train.py
  icefall/bpe_graph_compiler.py
  icefall/char_graph_compiler.py
  icefall/checkpoint.py
  icefall/graph_compiler.py
  icefall/utils.py
Labels: ready

#678 Add low-order density ratio in RNNLM shallow fusion
  .github/scripts/run-librispeech-lstm-transducer-stateless2-2022-09-03.yml
  .github/workflows/run-librispeech-lstm-transducer-stateless2-2022-09-03.yml
  egs/librispeech/ASR/RESULTS.md
  egs/librispeech/ASR/lstm_transducer_stateless2/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py
  egs/librispeech/ASR/pruned_transducer_stateless3/decode.py
Labels: LODR
