Repository k2-fsa/icefall, pull requests merged in 2022-12, with the labels that each got.

#720 Update RNNLM training scripts
  .github/workflows/run-ptb-rnn-lm.yml
  egs/librispeech/ASR/local/train_bpe_model.py
  egs/ptb/LM/prepare.sh
  egs/ptb/LM/rnn_lm
  egs/ptb/LM/train-rnn-lm.sh
  icefall/rnn_lm/compute_perplexity.py
  icefall/rnn_lm/dataset.py
  icefall/rnn_lm/train.py
Labels: rnnlm

#396 MGB2
  .gitignore
  egs/mgb2/ASR/README.md
  egs/mgb2/ASR/RESULTS.md
  egs/mgb2/ASR/conformer_ctc/__init__.py
  egs/mgb2/ASR/conformer_ctc/ali.py
  egs/mgb2/ASR/conformer_ctc/asr_datamodule.py
  egs/mgb2/ASR/conformer_ctc/compile_hlg.py
  egs/mgb2/ASR/conformer_ctc/compute_fbank_musan.py
  egs/mgb2/ASR/conformer_ctc/conformer.py
  egs/mgb2/ASR/conformer_ctc/convert_transcript_words_to_tokens.py
  egs/mgb2/ASR/conformer_ctc/decode.py
  egs/mgb2/ASR/conformer_ctc/download_lm.py
  egs/mgb2/ASR/conformer_ctc/export.py
  egs/mgb2/ASR/conformer_ctc/generate_unique_lexicon.py
  egs/mgb2/ASR/conformer_ctc/label_smoothing.py
  egs/mgb2/ASR/conformer_ctc/pretrained.py
  egs/mgb2/ASR/conformer_ctc/subsampling.py
  egs/mgb2/ASR/conformer_ctc/test_label_smoothing.py
  egs/mgb2/ASR/conformer_ctc/test_subsampling.py
  egs/mgb2/ASR/conformer_ctc/test_transformer.py
  egs/mgb2/ASR/conformer_ctc/train.py
  egs/mgb2/ASR/conformer_ctc/transformer.py
  egs/mgb2/ASR/local/__init__.py
  egs/mgb2/ASR/local/compile_hlg.py
  egs/mgb2/ASR/local/compute_fbank_mgb2.py
  egs/mgb2/ASR/local/compute_fbank_musan.py
  egs/mgb2/ASR/local/convert_transcript_words_to_tokens.py
  egs/mgb2/ASR/local/display_manifest_statistics.py
  egs/mgb2/ASR/local/generate_unique_lexicon.py
  egs/mgb2/ASR/local/prep_mgb2_lexicon.sh
  egs/mgb2/ASR/local/prepare_lang.py
  egs/mgb2/ASR/local/prepare_lang_bpe.py
  egs/mgb2/ASR/local/prepare_mgb2_lexicon.py
  egs/mgb2/ASR/local/test_prepare_lang.py
  egs/mgb2/ASR/prepare.sh
  egs/mgb2/ASR/pruned_transducer_stateless5/__init__.py
  egs/mgb2/ASR/pruned_transducer_stateless5/asr_datamodule.py
  egs/mgb2/ASR/pruned_transducer_stateless5/beam_search.py
  egs/mgb2/ASR/pruned_transducer_stateless5/conformer.py
  egs/mgb2/ASR/pruned_transducer_stateless5/decode.py
  egs/mgb2/ASR/pruned_transducer_stateless5/decoder.py
  egs/mgb2/ASR/pruned_transducer_stateless5/encoder_interface.py
  egs/mgb2/ASR/pruned_transducer_stateless5/export.py
  egs/mgb2/ASR/pruned_transducer_stateless5/joiner.py
  egs/mgb2/ASR/pruned_transducer_stateless5/model.py
  egs/mgb2/ASR/pruned_transducer_stateless5/optim.py
  egs/mgb2/ASR/pruned_transducer_stateless5/pretrained.py
  egs/mgb2/ASR/pruned_transducer_stateless5/scaling.py
  egs/mgb2/ASR/pruned_transducer_stateless5/test_model.py
  egs/mgb2/ASR/pruned_transducer_stateless5/train.py
  egs/mgb2/ASR/shared
  icefall/diagnostics.py
Labels: ready

#717 Convert conv-emformer to ncnn
  .github/scripts/run-librispeech-conv-emformer-transducer-stateless2-2022-12-05.sh
  .github/scripts/run-librispeech-lstm-transducer-stateless2-2022-09-03.sh
  .github/workflows/run-librispeech-conv-emformer-transducer-stateless2-2022-12-05.yml
  .github/workflows/run-librispeech-lstm-transducer-stateless2-2022-09-03.yml
  egs/librispeech/ASR/conv_emformer_transducer_stateless2/emformer2.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless2/export-for-ncnn.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless2/jit_pretrained.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless2/lstmp.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless2/scaling_converter.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless2/streaming-ncnn-decode.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless2/train2.py
Labels: ncnn

#751 Add AliMeeting multi-condition training recipe
  egs/alimeeting/ASR_v2/README.md
  egs/alimeeting/ASR_v2/RESULTS.md
  egs/alimeeting/ASR_v2/local/__init__.py
  egs/alimeeting/ASR_v2/local/compute_fbank_alimeeting.py
  egs/alimeeting/ASR_v2/local/compute_fbank_musan.py
  egs/alimeeting/ASR_v2/local/prepare_alimeeting_enhanced.py
  egs/alimeeting/ASR_v2/local/prepare_alimeeting_gss.sh
  egs/alimeeting/ASR_v2/local/prepare_char.py
  egs/alimeeting/ASR_v2/local/prepare_words.py
  egs/alimeeting/ASR_v2/local/text2segments.py
  egs/alimeeting/ASR_v2/local/text2token.py
  egs/alimeeting/ASR_v2/prepare.sh
  egs/alimeeting/ASR_v2/pruned_transducer_stateless7/__init__.py
  egs/alimeeting/ASR_v2/pruned_transducer_stateless7/asr_datamodule.py
  egs/alimeeting/ASR_v2/pruned_transducer_stateless7/beam_search.py
  egs/alimeeting/ASR_v2/pruned_transducer_stateless7/decode.py
  egs/alimeeting/ASR_v2/pruned_transducer_stateless7/decoder.py
  egs/alimeeting/ASR_v2/pruned_transducer_stateless7/encoder_interface.py
  egs/alimeeting/ASR_v2/pruned_transducer_stateless7/export.py
  egs/alimeeting/ASR_v2/pruned_transducer_stateless7/jit_pretrained.py
  egs/alimeeting/ASR_v2/pruned_transducer_stateless7/joiner.py
  egs/alimeeting/ASR_v2/pruned_transducer_stateless7/model.py
  egs/alimeeting/ASR_v2/pruned_transducer_stateless7/optim.py
  egs/alimeeting/ASR_v2/pruned_transducer_stateless7/pretrained.py
  egs/alimeeting/ASR_v2/pruned_transducer_stateless7/scaling.py
  egs/alimeeting/ASR_v2/pruned_transducer_stateless7/scaling_converter.py
  egs/alimeeting/ASR_v2/pruned_transducer_stateless7/test_model.py
  egs/alimeeting/ASR_v2/pruned_transducer_stateless7/train.py
  egs/alimeeting/ASR_v2/pruned_transducer_stateless7/zipformer.py
  egs/alimeeting/ASR_v2/shared
Labels: ready

#796 fix bug for triton onnx export
  egs/wenetspeech/ASR/pruned_transducer_stateless5/conformer.py
Labels: bug, onnx
