Repository k2-fsa/icefall, pull requests merged in 2022-08, with the labels that each got.

#501 Support exporting to ONNX format
  .github/scripts/run-librispeech-pruned-transducer-stateless3-2022-05-13.sh
  .github/workflows/run-librispeech-pruned-transducer-stateless3-2022-05-13.yml
  egs/librispeech/ASR/pruned_transducer_stateless2/conformer.py
  egs/librispeech/ASR/pruned_transducer_stateless2/decoder.py
  egs/librispeech/ASR/pruned_transducer_stateless2/joiner.py
  egs/librispeech/ASR/pruned_transducer_stateless2/scaling.py
  egs/librispeech/ASR/pruned_transducer_stateless3/export.py
  egs/librispeech/ASR/pruned_transducer_stateless3/jit_pretrained.py
  egs/librispeech/ASR/pruned_transducer_stateless3/onnx_check.py
  egs/librispeech/ASR/pruned_transducer_stateless3/onnx_pretrained.py
  egs/librispeech/ASR/pruned_transducer_stateless3/pretrained.py
  egs/librispeech/ASR/pruned_transducer_stateless3/scaling_converter.py
  egs/librispeech/ASR/pruned_transducer_stateless3/test_scaling_converter.py
  egs/librispeech/ASR/pruned_transducer_stateless3/train.py
  requirements-ci.txt
  requirements.txt
Labels: ready, onnx

#517 Convert ScaledEmbedding to nn.Embedding for inference.
  egs/librispeech/ASR/pruned_transducer_stateless2/scaling.py
  egs/librispeech/ASR/pruned_transducer_stateless3/scaling_converter.py
  egs/librispeech/ASR/pruned_transducer_stateless3/test_scaling_converter.py
  icefall/decode.py
Labels: onnx

#518 Merging onnx models
  .github/scripts/run-librispeech-pruned-transducer-stateless3-2022-05-13.sh
  egs/librispeech/ASR/pruned_transducer_stateless3/export.py
  egs/librispeech/ASR/pruned_transducer_stateless3/onnx_check_all_in_one.py
  requirements-ci.txt
  requirements.txt
Labels: ready, onnx

#421 Fix loading sampler state dict.
  egs/librispeech/ASR/pruned_transducer_stateless/train.py
  egs/librispeech/ASR/pruned_transducer_stateless2/train.py
  egs/librispeech/ASR/pruned_transducer_stateless3/train.py
  egs/librispeech/ASR/pruned_transducer_stateless4/train.py
  egs/librispeech/ASR/pruned_transducer_stateless5/train.py
  egs/librispeech/ASR/pruned_transducer_stateless6/train.py
Labels: ready

#522 Sort results to make it more convenient to compare decoding results
  egs/aidatatang_200zh/ASR/pruned_transducer_stateless2/decode.py
  egs/aishell/ASR/conformer_ctc/decode.py
  egs/aishell/ASR/conformer_mmi/decode.py
  egs/aishell/ASR/pruned_transducer_stateless3/decode.py
  egs/aishell/ASR/tdnn_lstm_ctc/decode.py
  egs/aishell/ASR/transducer_stateless/decode.py
  egs/aishell/ASR/transducer_stateless_modified-2/decode.py
  egs/aishell/ASR/transducer_stateless_modified/decode.py
  egs/aishell2/ASR/pruned_transducer_stateless5/decode.py
  egs/aishell4/ASR/pruned_transducer_stateless5/decode.py
  egs/alimeeting/ASR/pruned_transducer_stateless2/decode.py
  egs/gigaspeech/ASR/conformer_ctc/decode.py
  egs/gigaspeech/ASR/pruned_transducer_stateless2/decode.py
  egs/librispeech/ASR/conformer_ctc/decode.py
  egs/librispeech/ASR/conformer_ctc2/decode.py
  egs/librispeech/ASR/conformer_mmi/decode.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless/decode.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless/stream.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless/streaming_decode.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless2/decode.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless2/streaming_decode.py
  egs/librispeech/ASR/pruned_stateless_emformer_rnnt2/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless/decode_stream.py
  egs/librispeech/ASR/pruned_transducer_stateless/streaming_decode.py
  egs/librispeech/ASR/pruned_transducer_stateless2/conformer.py
  egs/librispeech/ASR/pruned_transducer_stateless2/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless2/decoder.py
  egs/librispeech/ASR/pruned_transducer_stateless2/joiner.py
  egs/librispeech/ASR/pruned_transducer_stateless2/scaling.py
  egs/librispeech/ASR/pruned_transducer_stateless2/streaming_decode.py
  egs/librispeech/ASR/pruned_transducer_stateless3/decode-giga.py
  egs/librispeech/ASR/pruned_transducer_stateless3/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless3/scaling_converter.py
  egs/librispeech/ASR/pruned_transducer_stateless3/streaming_decode.py
  egs/librispeech/ASR/pruned_transducer_stateless4/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless4/streaming_decode.py
  egs/librispeech/ASR/pruned_transducer_stateless5/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless5/streaming_decode.py
  egs/librispeech/ASR/pruned_transducer_stateless6/decode.py
  egs/librispeech/ASR/tdnn_lstm_ctc/decode.py
  egs/librispeech/ASR/transducer/decode.py
  egs/librispeech/ASR/transducer_lstm/decode.py
  egs/librispeech/ASR/transducer_stateless/decode.py
  egs/librispeech/ASR/transducer_stateless2/decode.py
  egs/librispeech/ASR/transducer_stateless_multi_datasets/decode.py
  egs/spgispeech/ASR/pruned_transducer_stateless2/decode.py
  egs/tal_csasr/ASR/pruned_transducer_stateless5/decode.py
  egs/tedlium3/ASR/pruned_transducer_stateless/decode.py
  egs/tedlium3/ASR/transducer_stateless/decode.py
  egs/timit/ASR/tdnn_ligru_ctc/decode.py
  egs/timit/ASR/tdnn_lstm_ctc/decode.py
  egs/wenetspeech/ASR/pruned_transducer_stateless2/decode.py
  egs/wenetspeech/ASR/pruned_transducer_stateless5/decode.py
  egs/wenetspeech/ASR/pruned_transducer_stateless5/decode_stream.py
  egs/wenetspeech/ASR/pruned_transducer_stateless5/streaming_decode.py
  egs/yesno/ASR/tdnn/decode.py
  egs/yesno/ASR/transducer/decode.py
  icefall/__init__.py
  icefall/utils.py
Labels: ready

#531 propagate changes from #525 to other librispeech recipes
  egs/librispeech/ASR/pruned_transducer_stateless/model.py
  egs/librispeech/ASR/pruned_transducer_stateless/train.py
  egs/librispeech/ASR/pruned_transducer_stateless2/train.py
  egs/librispeech/ASR/pruned_transducer_stateless3/model.py
  egs/librispeech/ASR/pruned_transducer_stateless3/train.py
  egs/librispeech/ASR/pruned_transducer_stateless4/train.py
  egs/librispeech/ASR/pruned_transducer_stateless5/train.py
  egs/librispeech/ASR/pruned_transducer_stateless6/model.py
  egs/librispeech/ASR/pruned_transducer_stateless6/train.py
  icefall/utils.py
Labels: ready

#533 Fix not enough values to unpack error .
  egs/aishell/ASR/conformer_ctc/decode.py
  egs/aishell/ASR/conformer_mmi/decode.py
  egs/aishell/ASR/pruned_transducer_stateless3/decode.py
  egs/aishell/ASR/tdnn_lstm_ctc/decode.py
  egs/aishell/ASR/transducer_stateless/decode.py
  egs/aishell/ASR/transducer_stateless_modified-2/decode.py
  egs/aishell/ASR/transducer_stateless_modified/decode.py
  egs/spgispeech/ASR/pruned_transducer_stateless2/decode.py
Labels: ready
