Repository k2-fsa/icefall, pull requests merged in 2022-06, with the labels that each got.

#388 Update RESULTS.md
  egs/librispeech/ASR/RESULTS.md
  egs/librispeech/ASR/pruned_transducer_stateless4/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless4/export.py
Labels: ready

#400 [Ready to merge] Do a change for wenetspeech/pruned_transducer_stateless2/decode.py
  egs/wenetspeech/ASR/pruned_transducer_stateless2/decode.py
Labels: ready

#402 Fix exporting emformer with torchscript using torch 1.6.0
  egs/librispeech/ASR/pruned_stateless_emformer_rnnt2/emformer.py
Labels: ready

#404 Replace LilcomChunkyWriter with ChunkedLilcomHdf5Writer.
  egs/aishell/ASR/local/compute_fbank_aidatatang_200zh.py
  egs/aishell/ASR/local/compute_fbank_aishell.py
  egs/librispeech/ASR/local/compute_fbank_librispeech.py
  egs/librispeech/ASR/local/compute_fbank_musan.py
  egs/spgispeech/ASR/local/compute_fbank_musan.py
  egs/spgispeech/ASR/local/compute_fbank_spgispeech.py
  egs/timit/ASR/local/compute_fbank_timit.py
  egs/yesno/ASR/local/compute_fbank_yesno.py
Labels: run-decode

#389 Emformer with conv module and scaling mechanism
  .flake8
  egs/librispeech/ASR/README.md
  egs/librispeech/ASR/RESULTS.md
  egs/librispeech/ASR/conv_emformer_transducer_stateless/asr_datamodule.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless/beam_search.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless/decode.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless/decoder.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless/emformer.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless/encoder_interface.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless/export.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless/joiner.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless/model.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless/optim.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless/scaling.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless/stream.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless/streaming_decode.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless/test_emformer.py
  egs/librispeech/ASR/conv_emformer_transducer_stateless/train.py
  egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py
Labels: ready

#435 Fix warmup
  egs/librispeech/ASR/conv_emformer_transducer_stateless/train.py
  egs/librispeech/ASR/pruned_transducer_stateless2/train.py
  egs/librispeech/ASR/pruned_transducer_stateless3/train.py
  egs/librispeech/ASR/pruned_transducer_stateless4/train.py
  egs/librispeech/ASR/pruned_transducer_stateless5/train.py
  egs/librispeech/ASR/pruned_transducer_stateless6/train.py
Labels: ready

#437 [Ready to merge] Do some changes for export.py
  egs/aidatatang_200zh/ASR/pruned_transducer_stateless2/export.py
  egs/aishell/ASR/transducer_stateless/export.py
  egs/aishell/ASR/transducer_stateless_modified-2/export.py
  egs/aishell/ASR/transducer_stateless_modified/export.py
  egs/aishell4/ASR/pruned_transducer_stateless5/export.py
  egs/alimeeting/ASR/pruned_transducer_stateless2/export.py
  egs/gigaspeech/ASR/pruned_transducer_stateless2/export.py
  egs/spgispeech/ASR/pruned_transducer_stateless2/export.py
  egs/tedlium3/ASR/pruned_transducer_stateless/export.py
  egs/tedlium3/ASR/transducer_stateless/export.py
  egs/wenetspeech/ASR/pruned_transducer_stateless2/export.py
Labels: ready

#429 Upload extracted codebook indexes
  egs/librispeech/ASR/distillation_with_hubert.sh
  egs/librispeech/ASR/pruned_transducer_stateless6/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless6/extract_codebook_index.py
  egs/librispeech/ASR/pruned_transducer_stateless6/train.py
  egs/librispeech/ASR/pruned_transducer_stateless6/vq_utils.py
Labels: ready

#420 Add fast_beam_search_nbest.
  .github/scripts/run-librispeech-pruned-transducer-stateless5-2022-05-13.sh
  .github/workflows/test.yml
  egs/librispeech/ASR/pruned_transducer_stateless/beam_search.py
  egs/librispeech/ASR/pruned_transducer_stateless/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py
  egs/librispeech/ASR/pruned_transducer_stateless2/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless3/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless4/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless5/decode.py
  icefall/decode.py
Labels: ready, run-decode

#439 [Ready to be merged] Add RNN-LM to Conformer-CTC decoding
  egs/librispeech/ASR/RESULTS.md
  egs/librispeech/ASR/conformer_ctc/decode.py
  egs/librispeech/ASR/local/download_lm.py
  egs/librispeech/ASR/local/prepare_lm_training_data.py
  egs/librispeech/ASR/local/sort_lm_training_data.py
  egs/librispeech/ASR/local/train_bpe_model.py
  egs/librispeech/ASR/prepare.sh
  egs/ptb/LM/README.md
  egs/ptb/LM/local/prepare_lm_training_data.py
  egs/ptb/LM/local/sort_lm_training_data.py
  egs/ptb/LM/local/test_prepare_lm_training_data.py
  egs/ptb/LM/local/train_bpe_model.py
  egs/ptb/LM/prepare.sh
  egs/ptb/LM/shared
  icefall/decode.py
  icefall/dist.py
  icefall/rnn_lm/compute_perplexity.py
  icefall/rnn_lm/dataset.py
  icefall/rnn_lm/export.py
  icefall/rnn_lm/model.py
  icefall/rnn_lm/test_dataset.py
  icefall/rnn_lm/test_dataset_ddp.py
  icefall/rnn_lm/test_model.py
  icefall/rnn_lm/train.py
  icefall/utils.py
Labels: ready

#443 Fix errors for soft connection in egs/ptb/LM/local
  egs/ptb/LM/local/prepare_lm_training_data.py
  egs/ptb/LM/local/train_bpe_model.py
Labels: ready

#380 Using streaming conformer as transducer encoder
  .github/scripts/run-librispeech-streaming-pruned-transducer-stateless2-2022-06-26.sh
  .github/workflows/run-librispeech-streaming-transducer-stateless2-2022-06-26.yml
  egs/librispeech/ASR/RESULTS.md
  egs/librispeech/ASR/pruned_transducer_stateless/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless/decode_stream.py
  egs/librispeech/ASR/pruned_transducer_stateless/export.py
  egs/librispeech/ASR/pruned_transducer_stateless/pretrained.py
  egs/librispeech/ASR/pruned_transducer_stateless/streaming_decode.py
  egs/librispeech/ASR/pruned_transducer_stateless/test_model.py
  egs/librispeech/ASR/pruned_transducer_stateless/train.py
  egs/librispeech/ASR/pruned_transducer_stateless2/conformer.py
  egs/librispeech/ASR/pruned_transducer_stateless2/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless2/decode_stream.py
  egs/librispeech/ASR/pruned_transducer_stateless2/export.py
  egs/librispeech/ASR/pruned_transducer_stateless2/joiner.py
  egs/librispeech/ASR/pruned_transducer_stateless2/pretrained.py
  egs/librispeech/ASR/pruned_transducer_stateless2/streaming_decode.py
  egs/librispeech/ASR/pruned_transducer_stateless2/test_model.py
  egs/librispeech/ASR/pruned_transducer_stateless2/train.py
  egs/librispeech/ASR/pruned_transducer_stateless3/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless3/decode_stream.py
  egs/librispeech/ASR/pruned_transducer_stateless3/export.py
  egs/librispeech/ASR/pruned_transducer_stateless3/pretrained.py
  egs/librispeech/ASR/pruned_transducer_stateless3/streaming_decode.py
  egs/librispeech/ASR/pruned_transducer_stateless3/test_model.py
  egs/librispeech/ASR/pruned_transducer_stateless3/train.py
  egs/librispeech/ASR/pruned_transducer_stateless4/decode.py
  egs/librispeech/ASR/pruned_transducer_stateless4/decode_stream.py
  egs/librispeech/ASR/pruned_transducer_stateless4/export.py
  egs/librispeech/ASR/pruned_transducer_stateless4/streaming_decode.py
  egs/librispeech/ASR/pruned_transducer_stateless4/test_model.py
  egs/librispeech/ASR/pruned_transducer_stateless4/train.py
  egs/librispeech/ASR/transducer_stateless/conformer.py
  icefall/__init__.py
  icefall/utils.py
Labels: ready, run-decode

#453 Use load_manifest_lazy to load cuts_L.jsonl.gz in wenetspeech
  egs/wenetspeech/ASR/pruned_transducer_stateless2/asr_datamodule.py
Labels: ready

#452 Modification about random combine
  egs/librispeech/ASR/pruned_transducer_stateless5/conformer.py
Labels: ready
